### ISSUE TITLE
Missing dependency uritemplate.py

### ISSUE THREAD

**Issue by varunwy** [conda-forge/google-api-python-client-feedstock#6]
Package url : https://conda.anaconda.org/conda-forge/linux-64/google-api-python-client-1.6.2-py27_0.tar.bz2

```
Traceback (most recent call last):
  File "/home/app/httpserver/router.py", line 4, in <module>
    from apiclient.discovery import build
  File "/usr/local/mypython/envs/cherry/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/mypython/envs/cherry/lib/python2.7/site-packages/apiclient/__init__.py", line 19, in <module>
    from googleapiclient import discovery
  File "/usr/local/mypython/envs/cherry/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/mypython/envs/cherry/lib/python2.7/site-packages/googleapiclient/discovery.py", line 53, in <module>
    import uritemplate
  File "/usr/local/mypython/envs/cherry/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named uritemplate
```
Installing uritemplate.py package from https://conda.anaconda.org/conda-forge/linux-64/uritemplate.py-3.0.2-py27_0.tar.bz2 fixed the error.

Similar discussion here: https://github.com/sigmavirus24/github3.py/issues/634

**Comment by hrishikeshrt** [comment]
Same issue, and same solution, `conda install uritemplate.py` (even if `google-api-python-client` already installs `uritemplate`.

**Comment by ocefpaf** [comment]
This was fixed some time ago: https://github.com/conda-forge/google-api-python-client-feedstock/blob/master/recipe/meta.yaml#L26
